mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include("polls.urls")),

]

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"


urlpatterns = [
    path("", views.index, name="index"),
    path("index", views.index, name="index"),
    path("test", views.test_view, name="test_view"),
    

    # ex: /polls/5/
    path("<int:question_id>/", views.detail, name="detail"),
    # ex: /polls/5/results/
    path("<int:question_id>/results/", views.results, name="results"),
    # ex: /polls/5/vote/
    path("<int:question_id>/vote/", views.vote, name="vote"),

    path("<int:question_id>/addchoice/", views.addchoice, name="addchoice"),
    path("<int:question_id>/newchoice/", views.newchoice, name="newchoice"),
    path("<int:question_id>/resetvote/", views.resetvote, name="resetvote"),
    path("addques/", views.addques, name="addques"),
    path("newques/", views.newques, name="newques"),

]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.http import Http404
from django.urls import reverse
from django.utils import timezone
from .models import Question, Choice


def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    data = {"latest_question_list": latest_question_list}
    return render(request, "polls/index.html", data)

def test_view(request):
    return HttpResponse("Test View.")

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/detail.html", {"question": question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))


def addchoice(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    # return HttpResponse("add choice view")
    return render(request, "polls/addchoice.html", {"question": question})


def newchoice(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        new_choice = request.POST["new_choice"]
        if not new_choice:
            raise KeyError
    except (KeyError):
        # Redisplay the question detail form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "Choice could not be added",
            },
        )
    else:
        newchoice = Choice(
            question = question,
            choice_text = new_choice,
        )
        newchoice.save()
        return HttpResponseRedirect(reverse("polls:detail", args=(question.id,)))


def resetvote(request, question_id):
    # return HttpResponse("rest votes")
    question = get_object_or_404(Question, pk=question_id)
    for choice in question.choice_set.all():
        choice.votes = 0
        choice.save()
    return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

def addques(request):
    # return HttpResponse("add question view")
    return render(request, "polls/addques.html")


def newques(request):
    # return HttpResponse("new question view")

    try:
        new_question = request.POST["new_ques"]
        if not new_question:
            raise KeyError
    except (KeyError):
        # Redisplay the index file.
        return render(
            request,
            "polls/addques.html",
            {
                # "question": question,
                "error_message": "question could not be added",
            },
        )
    else:
        try:
            for question in Question.objects.all():
                if question.question_text == new_question:
                    raise KeyError
        except (KeyError):
             # Redisplay the index file.
            return render(
                request,
                "polls/addques.html",
                {
                    # "question": question,
                    "error_message": "question already exist.",
                },
            )
        else:
            newquestion = Question(
                question_text = new_question,
                pub_date = timezone.now(),
            )
            newquestion.save()
            return HttpResponseRedirect(reverse("polls:index"))

polls/templates/polls/addchoice.html
<!-- <p>saman</p> -->
<form action="{% url 'polls:newchoice' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>Add new choice for {{ question.question_text }} </h1></legend>
        <label>New Choice</label>
        <input type="text" name="new_choice">
    </fieldset>
    <input type="submit" value="Add choice">
</form>

polls/templates/polls/addques.html
<!-- <p>saman</p> -->
<form action="{% url 'polls:newques' %}" method="post">
    {% csrf_token %}
    <fieldset>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

        <legend><h1>Add new question</h1></legend>
        <label>New Question</label>
        <input type="text" name="new_ques">
    </fieldset>
    <input type="submit" value="Add">
</form>

polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <a href="{% url 'polls:addchoice' question.id %}">add choice</a>
    <input type="submit" value="Vote">
    </form>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<a href="{% url 'polls:addques' %}" >Add new question</a>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a><br>

<a href="{% url 'polls:resetvote' question.id %}" >reset votes</a>